clear;
close all;
clc;
% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 06-Nov-2023 20:13:58
% FIR Window Lowpass filter designed using the FIR1 function.
% Fpass = 20 KHz, Fstop = 28 KHz , Fsample = 160 KHz
% As = 50 db in stopband
% All frequency values are in kHz.
Fs = 160;  % Sampling Frequency

N    = 66;       % Order
Fc   = 24;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);

%% Finally , Apply the FIR Filter
% Design the ideal low-pass filter
% fir1 is designing FIR filter with the windowing method
% Plot the filter's frequency response
h_n  = fir1(N, Fc/(Fs/2), 'low', win, flag);
freqz(h_n, 1, 1024, Fs);

% Display the filter coefficients
disp("Filter Coefficients:");
disp(h_n);

Length = N + 1;

h_n_scaled = [1:Length];
% Convert from decimal to 16-bit fixed point binary format
for ii = 1:Length
    h_n_scaled(ii) = h_n(ii) * 2^15;
end
        
%% Capture the filter coefficient in a text file
% Open a file for writing
fileID = fopen('FIR_Coeff.txt', 'w');
h_n_scaled_hex = dec2hex(round(h_n_scaled),4);

% Write each value with a line separator
yy = cellstr(h_n_scaled_hex);
fprintf(fileID, '%s \n', yy{:});

% Close the file
fclose(fileID);

